media_entity_spotify.settings:
  type: config_object
  label: 'Media entity Spotify settings'
  mapping:
    thumbnail_destination:
      type: string
      label: 'Destination for thumbnails'

media.source.spotify:
  type: media_source
  label: 'Spotify media source configuration'
  mapping:
    source_field:
      type: string
      label: 'Field on the media entity that stores Spotify URL'

field.formatter.settings.spotify_embed:
  type: mapping
  label: 'Field display format settings'
  mapping:
    playlist:
      type: mapping
      label: 'Field settings for playlist/album'
      mapping:
        theme:
          type: string
          label: 'Theme'
        view:
          type: string
          label: 'View'
        width:
          type: string
          label: 'Width'
        height:
          type: string
          label: 'Height'
    track:
      type: mapping
      label: 'Field settings for track'
      mapping:
        theme:
          type: string
          label: 'Theme'
        view:
          type: string
          label: 'View'
        width:
          type: string
          label: 'Width'
        height:
          type: string
          label: 'Height'
